-- CreateEnum
CREATE TYPE "STATUS_ACCOUNT" AS ENUM ('GOD', 'TESTEUR', 'BASIC', 'PRENIUM', 'FREE');

-- AlterTable
ALTER TABLE "accounts" ADD COLUMN     "status" "STATUS_ACCOUNT" NOT NULL DEFAULT 'FREE';
